### ISSUE TITLE
Swift support?

### ISSUE THREAD

**Issue by skywinder** [stefanceriu/SCXcodeSwitchExpander#10]
Is your plugin support swift?

**Comment by jerometonnelier** [comment]
It would be awesome since Swift complains if not all the cases are filled ;)

**Comment by skywinder** [comment]
@stefanceriu Any updates?

**Comment by stefanceriu** [comment]
Hi guys,

Considering how much more complex switching in Swift is, I have doubts that this can even be achieved through a plugin. The amount of info I can get from Xcode is nowhere close to what I need to get this working.

Have a look at this (scroll down to the switch statement):
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Statements.html

If you have any good ideas and would like to give this a shot, pull requests are more than welcome.

Cheers,
Stefan
