### ISSUE TITLE
case template suggestion

### ISSUE THREAD

**Issue by zendobk** [stefanceriu/SCXcodeSwitchExpander#13]
current: `case x: <#statement#> break;`

suggest: `case x: {<#statement#>} break;`

reason: Xcode internal autocompletion not working without `{}`

**Comment by stefanceriu** [comment]
Hi, what do you mean by 'Xcode's internal autocompletion not working' ?

**Comment by zendobk** [comment]
Thanks for your reply :+1: 

It means...
For example: If I type "[MyClass shared...", Xcode would not automatically suggest my instance "[MyClass sharedInstance]"

Sorry for my poor English...

**Comment by stefanceriu** [comment]
I'm not seeing the same problem on my side, are you sure it's a problem coming from the switch expander and not an Xcode thing ?

**Comment by zendobk** [comment]
Not plugins issue. It's Xcode issue which easy to be fixed with `{}`
Anyway, you can close this issue without problems.
Thanks!
![screen shot 2015-04-21 at 11 05 24 am](https://cloud.githubusercontent.com/assets/1290396/7245504/76c6c630-e816-11e4-8f62-10d0d07c70af.png)
![screen shot 2015-04-21 at 11 05 32 am](https://cloud.githubusercontent.com/assets/1290396/7245505/7718306a-e816-11e4-8ee9-1165e16d9e62.png)

**Comment by stefanceriu** [comment]
Curly brackets now available :smile:

**Comment by zendobk** [comment]
Seem to be new suggestion is not better than I think. Sorry.
