### ISSUE TITLE
c++ support now working

### ISSUE THREAD

**Issue by p0fi** [stefanceriu/SCXcodeSwitchExpander#16]
Hi, thanks for trying to make the C++ enums working but it somehow doesn't work for my C++ project :(

here is the enum:

```
typedef enum {
	CASE1 = 0x00,
	CASE2 = 0x01,
	CASE3 = 0x02,
	CASE4 = 0x03,
	CASE5 = 0x04,
	CASE6 = 0x05,
	CASE7 = 0x06, 
	CASE8 = 0x07  
} testEnum;
```

but the autocomplete doesn't kick in. Still only the default Xcode snippet and after filling the expression nothing happens. I'm using Xcode 6.2.

**Comment by stefanceriu** [comment]
I won't work on anonymous enums but you can change it to this:
```
typedef testEnum enum {
    CASE1 = 0x00,
    CASE2 = 0x01,
    CASE3 = 0x02,
    CASE4 = 0x03,
    CASE5 = 0x04,
    CASE6 = 0x05,
    CASE7 = 0x06, 
    CASE8 = 0x07  
} testEnum;
```

**Comment by p0fi** [comment]
This won't work since the compiler throws 3 warnings on this one:

1. `Unknown type name 'testEnum'`
2. `Expected unqualified-id`
3. `C++ requires a type specifier for all declarations`

**Comment by stefanceriu** [comment]
Ups, my bad, it's the other way around:

```typedef enum testEnum {
	CASE1 = 0x00,
	CASE2 = 0x01,
	CASE3 = 0x02,
	CASE4 = 0x03,
	CASE5 = 0x04,
	CASE6 = 0x05,
	CASE7 = 0x06,
	CASE8 = 0x07
} testEnum;```

**Comment by p0fi** [comment]
Nice! It's working!
Thanks a lot!

**Comment by stefanceriu** [comment]
Perfect :smile:
