### ISSUE TITLE
Formatting options needed (regex, pattern and etc.)

### ISSUE THREAD

**Issue by gerchicov-bp** [stefanceriu/SCXcodeSwitchExpander#20]
You should add a possibility to change a pattern for your plugin for example because:
1)it may take more time to format code generated with your plugin than to write the same code from zero;
2)"statement" is inserted by xcode. But in reality how often do you use it? In most cases you simply delete it because you don't need all the branches, you jump between code chunks nonlinearly (for example, you may implement the start and the finish behaviour first before main code)

**Comment by stefanceriu** [comment]
That sounds like a great idea, you should create a pull request for it !
