### ISSUE TITLE
Xcode 7.1 issues

### ISSUE THREAD

**Issue by jcarroll3** [stefanceriu/SCXcodeSwitchExpander#22]
It appears to load in xcode 7.1, but functionally doesn't actually perform the auto completion anymore

**Comment by stefanceriu** [comment]
Seems to be working just fine for me.

**Comment by jcarroll3** [comment]
:( o well

**Comment by stefanceriu** [comment]
You could try debugging it to see what's wrong. Just build, run and debug as you usually do.

**Comment by iKazakov** [comment]
7.1.1 - now working :( it worked before
