### ISSUE TITLE
Stop inserting the `default:` case (or remove it if found)

### ISSUE THREAD

**Issue by rastersize** [stefanceriu/SCXcodeSwitchExpander#24]
The `default:` should, IMO, generally not be included in a switch-statement as you lose one of the key advantages over using if-statements. Namely the compile time warnings for missing cases. This is very handy when, for example, adding a new enum value. Or to make sure you’re actually handling all the different cases.

Saves a bunch of time and potential hair-pulling :tada: 

Would love if `SCXcodeSwitchExpander` would therefore, by default, not include the `default:` statement. As well as removing it if inserted by the Xcode code snippet.

How do you feel regards to this @stefanceriu? If you’re positive towards the idea I could potentially try and whip up a PR for it.

**Comment by stefanceriu** [comment]
Sounds like a good idea to me, thank you for pointing it out.
I took the liberty of making the necessary changes so please do let me know if you have any problems with it after updating.
