### ISSUE TITLE
Autocomplete Crash

### ISSUE THREAD

**Issue by ZevsV** [stefanceriu/SCXcodeSwitchExpander#30]
[SwitchExpanderCrash.zip](https://github.com/stefanceriu/SCXcodeSwitchExpander/files/236171/SwitchExpanderCrash.zip)

**Comment by EZ-NET** [comment]
I found the reason of this problem.

Plugin will clash when two enum type have same name over two-tier. (eg. `StructA.NestedEnum.DeepNestedEnum` and `SomeStruct.StructB.NestedEnum.DeepNestedEnum`)

**Comment by stefanceriu** [comment]
Thank you, Tomohiro ! 💯

**Comment by stefanceriu** [comment]
Pushed it to a new version here https://github.com/stefanceriu/SCXcodeSwitchExpander/releases/tag/v1.2.1

**Comment by ZevsV** [comment]
Tanks a lot. It works.
