### ISSUE TITLE
Not working in Xcode Version 7.3.1 (7D1014)

### ISSUE THREAD

**Issue by masterkk** [stefanceriu/SCXcodeSwitchExpander#32]
I have added the xcode UUID. Still not working.

**Comment by stefanceriu** [comment]
What do you mean by "I have added the xcode UUID" ?
It's been in there for quite a while now - https://github.com/stefanceriu/SCXcodeSwitchExpander/commit/620afbf735cbb4b08b12c8b64fac006a59932e8b
