### ISSUE TITLE
Not working with parameters

### ISSUE THREAD

**Issue by revolter** [stefanceriu/SCXcodeSwitchExpander#9]
I have this enum declared this way:
```
typedef NS_ENUM(NSUInteger, DatabaseColumnType) {
	DatabaseColumnTypeInteger,
	DatabaseColumnTypeVarchar,
	DatabaseColumnTypeBoolean
};
```

and this method:

```
+ (NSString *)getNameForColumnType:(DatabaseColumnType)columnType {
	...
}
```

and inside it, the switch is not automatically filled with all the cases. I tried building the project but it still doesn't work. I also don't have any warning before it. Could it interfere with another plugin or Xcode setting?

**Comment by stefanceriu** [comment]
Your example is working for me so it might indeed be interfering with something else. What other plugins do you have installed ?

**Comment by revolter** [comment]
I have these plugins installed:

>Alcatraz
Backlight
CocoaPods
FuzzyAutocomplete
JDPluginManager
KSImageNamed
Lin
MCLog
NCSimulatorPlugin
OMColorSense
OMQuickHelp
SCXcodeSwitchExpander
UncrustifyPlugin
VVDocumenter-Xcode
XCFixin_TabAcceptsCompletions
XcodeColors
Xprop

I saw that in other places, it works with other enums and with this enum too.

I started playing with it and I could reproduce it. I have this:

```
+ (void)setDifficultyLevel:(DifficultyLevel)level {

	switch (lev) {
  case <#constant#>:
			<#statements#>
			break;

  default:
			break;
	}
}
```
If I go to the end of `lev` and I hit <kbd>CTRL</kbd> + <kbd>Space</kbd> and <kbd>Enter</kbd> it correctly autocompletes the switch. But if I have this:

```
+ (void)setDifficultyLevel:(DifficultyLevel)level {

	//	DatabaseColumnType type;
	switch (lev) {
  case <#constant#>:
			<#statements#>
			break;

  default:
			break;
	}
}
```
and I do the same thing, it ends up like this:
```
+ (void)setDifficultyLevel:(DifficultyLevel)level {

	//	DatabaseColumnType type;
	switch (level
			) {
  case <#constant#>:
			<#statements#>
			break;

  default:
			break;
	}
}
```
so it looks like the enter goes through and it actually enters a newline _(and autoindentation probably from Xcode)_.

Hope this helps you understand it better.

**Comment by stefanceriu** [comment]
Awesome, thank you. I'll have a look at it asap.

**Comment by stefanceriu** [comment]
Hey, sorry for the late reply. I've been trying and trying to reproduce this using a combination of other plugins but to no avail. Can you do me a favor and try removing some of the other plugins on your side to see if it starts working? (~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/)

**Comment by revolter** [comment]
No problem. I removed all plugins _(except this one, obviously)_ and it still doesn't work.

But I've seen another thing, if I move the method `getNameForColumnType` to the top of the file, IT WORKS. :-?

It's in a 2k lines file and something Xcode gets buggy on this file, visually, it's really odd and I didn't found others with the same problem. It shows up the same line twice, then it reverts, I click on a line and it changes to another, maybe that's the problem. Maybe it's a bug in Xcode or something with my code.

**Comment by stefanceriu** [comment]
Well, Xcode does have it's own share of problems but I'll try reproducing it that way, maybe I'm doing something wrong.

**Comment by revolter** [comment]
Ok, I found out the exact place of the problem. I have a method with a huge switch with 32 case statements, and right before it, it works, and right after it, it doesn't.

**Comment by revolter** [comment]
Finally, I found the exact line that caused this: `defaultLanguageName = @"বাংলা";` which is [Bengali language](http://www.wikiwand.com/en/Bengali_language)

**Comment by stefanceriu** [comment]
Wow, awesome :smile: I'll add that to my tests and debug the switch expander with it and I'll let you know if it's Xcode or me :)

**Comment by revolter** [comment]
Sure :smiley:

**Comment by stefanceriu** [comment]
Should be fixed now and as it turns out, converting the source code to a cString isn't too bright of an idea :grinning:

**Comment by revolter** [comment]
Awesome. Thanks!
